name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: dev-project-humayra
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Build Docker image and push to GCR
        run: |
          gcloud builds submit --tag gcr.io/dev-project-humayra/load-to-bigquery ./cloud-function

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy load-to-bigquery \
            --image gcr.io/dev-project-humayra/load-to-bigquery \
            --region us-east1 \
            --platform managed \
            --allow-unauthenticated
